### ISSUE TITLE
Error pulling up a Save

### ISSUE THREAD

**Issue by winkler1** [rolyatmax/copland#3]
Hi - nice job! Really like this. Especially the touch of the expanding buttons on mouseover to explain.

Loading a saved URL (https://tbaldw.in/copland/#/N4IgbiBcIEwHQAYQBoQCcogBYEsDmWKIOUA2qAM5QCcqAhpgggIzNPtvsdOec9fcBQ-sL5deIAL7JKNeo3HClLUcrGK1mqQF1JQA) is giving "Uncaught TypeError: (0 , _store.dispatch) is not a function"

Will show this to 5-year old tonight, thanks for putting this out there!

**Comment by rolyatmax** [comment]
Thanks for reporting this! So glad someone found some use out of it! Getting a fix out this morning!

**Comment by rolyatmax** [comment]
@winkler1 changes are out at https://tbaldw.in/copland - that URL should load now :smile:

**Comment by winkler1** [comment]
Fast turnaround! It's cool to see the Redux events going by in the console :+1:
